### ISSUE TITLE
Make it more robust and intelligent

### ISSUE THREAD

**Issue by blurHY** [blurHY/Horizon#10]
- [x] Database is empty
- [x] File not exist
- [x] Zeronet version

**Comment by krixano** [comment]
You can make the search engine appear like it's going faster, on a first query, limiting to the amount you want to show on the first page, then immediately doing another query for the next page - still with a limit. Then, when they click the next page, immediately show those results and query for the next page.

**Comment by blurHY** [comment]
I just do some complex things with javascript after sql query,but i won't use js to sort or filter 5 million data 😂
https://github.com/blurHY/Horizon/projects/1#card-13092259

**Comment by krixano** [comment]
Btw, in the code for Important Zites, I have code that constructs an sql query to query for zites based on relevance by seeing how many words in the query match whatever is in the database, as well as putting priority over certain fields. If you open the console on Important Zites or KxoNetwork while searching, you can see this.

**Comment by blurHY** [comment]
I used to write some title rank * 2 too.
And I'm going to implement PageRank algorithm for ranking.The site descriptions text data has been already published.So there is a lot of things need to be calculated for the final score.
Uh,i don't know it should be title rank * 2 or title rank * 1.5 or something else.

**Comment by blurHY** [comment]
Search 'b'
Takes 4.619s returns 73918 rows
Takes 3.743s with `limit 70000,3000`
Takes 3.312s with `limit 10,3000`
Maybe it will not be much quicker to query.

**Comment by krixano** [comment]
Did you try limiting to 10 or 20 or so? Also, even a half a second is significant imo.

**Comment by krixano** [comment]
If you do sorting/ordering in SQL, then that happens *before* limiting.

**Comment by blurHY** [comment]
So it's hard to improve.But if the new plugin system has been implemented and zeronet has moved to py3,it would be possible.

**Comment by krixano** [comment]
What things are you doing in js that you can't do in SQL currently?

**Comment by blurHY** [comment]
@krixano 
Merge pages that is the same zite.I think it could be done with `group_concat`,but we need to find a separator.If it can return a array for each item,the better.
