### ISSUE TITLE
Site appear not to be updating because content too large

### ISSUE THREAD

**Issue by slrslr** [blurHY/Horizon#12]
**Describe the bug**

Hello, i see the Horizon zite was not updated in last 3 days when i look on ZeroHello and it also shows 1 file update failure. So i open site, open its (0) menu and on the bottom of the menu i see it is content.json that failed.

then i check ZeroNet's debug.log to see these entries:

DEBUG    Site:1CjMsv..uxBn Can't update content.json
WARNING  Site:1CjMsv..uxBn content.json: verify sign error: VerifyError: Content too large 27887761B > 20971520B, aborting task... in ContentManager.py line 890 > ContentManager.py line 771

But on ZeroHello, it do not ask me to raise limit for the site, so this seems to me like a bug/issue..
Maybe it can happen because maybe i used files directly from github, i do not know.

What should i try?

**Environment (please complete the following information):**
 - OS: Ubuntu 16
 - Browser FF latest
 - Zeronet Revision 3597

**Comment by blurHY** [comment]
I upload the zite to github after signing and publishing it.So it should not be the reason.
You can try to run `Page.cmd("as","1CjMsvhJ2JsV4B5qo3FDHnF3mvRCcHuxBn","siteSetLimit","50"],console.log)` in the console of ZeroHello to raise the limit.Uh,i forgot that you can also use the sidebar.
Did you delete the whole folder of Horizon before you put the github copy? If you not,it may cause the issue.
Also that's a issue of zeronet.Because zeronet doesn't notice you that needs to raise limit.

**Comment by slrslr** [comment]
> You can try to run `Page.cmd("as","1CjMsvhJ2JsV4B5qo3FDHnF3mvRCcHuxBn","siteSetLimit","50"],console.log)` in the console of ZeroHello

I do not know how to access that command line, i am using Firefox and Ubuntu Linux now.

Anyway, in the Horizon site (0) menu i see the limit is 20MB and curent usage is 47% of the limit.

Then i see content.json no longer fails, "Check files" option finish and site says updated, no issue.
But last updated is 3 days ago (on ZeroHello next to Horizon site entry).

Should i try to delete horizon site and re-visit it to DL it? Or do you suggest cloning from the .git (making sure previous site folder is deleted as you said).

**Comment by blurHY** [comment]
Zeronet doesn't show the content too large issue.Please report it to Zeronet repo.
I published Horizon a day ago.So the last updated info is wrong.

![image](https://user-images.githubusercontent.com/33171396/45876398-26b2d680-bdcd-11e8-8f22-f87372c7f34c.png)

Raise the limit in the siderbar

**Comment by slrslr** [comment]
I set the SiteLimit for the Horizon site to 500MB (from within its (0) menu) and "Check files" & "Update", it both completed without any failed files, though last update date of the Horizon site is 18 September on ZeroHello (ZeroHello page was reloaded by Ctrl+F5 key). Should i post new issue on ZeroNet issue tracker?

**Comment by slrslr** [comment]
... and i forgot to post debug.log, sorry, here i found interesting lines that appears when i do "Check files" option on Horizon site:

`DEBUG    Site:1CjMsv..uxBn [INVALID] data/users/1JcHMiQxXHX9q3ZK2LF9rZjvg3MUtTpcK/data.json: **Invalid size**
DEBUG    Site:1CjMsv..uxBn Checked files in 0.00s... Found bad files: 1, Quick:True
DEBUG    Site:1CjMsv..uxBn content.json loadContent same json file, skipping
DEBUG    Site:1CjMsv..uxBn Bad files: {u'data/users/1JcHMiQxXHX9q3ZK2LF9rZjvg3MUtTpcK/data.json': 1}
DEBUG    Site:1CjMsv..uxBn Retry 1 bad files
DEBUG    Site:1CjMsv..uxBn New downloadFile pool: len: 1, only if bad: True
DEBUG    Site:1CjMsv..uxBn Ended downloadFile pool len: 1, skipped: 0
DEBUG    WorkerManager:1CjMsv..uxBn New task: data/users/1JcHMiQxXHX9q3ZK2LF9rZjvg3MUtTpcK/data.json, peer lock: None, priority: 3, optional_hash_id: None, tasks started: 1
DEBUG    WorkerManager:1CjMsv..uxBn Starting workers, tasks: 1, peers: 0, workers: 0
DEBUG    WorkerManager:1CjMsv..uxBn Added worker: 212.24.103.*:29535, workers: 1/5
DEBUG    WorkerManager:1CjMsv..uxBn Added worker: 7cyy64h*.onion:15663, workers: 2/5
DEBUG    WorkerManager:1CjMsv..uxBn Added worker: 6wvuej*.onion:14412, workers: 3/5
DEBUG    WorkerManager:1CjMsv..uxBn Added worker: c6oc6b3*.onion:60239, workers: 4/5
DEBUG    WorkerManager:1CjMsv..uxBn Added worker: 109.202.107.*:60239, workers: 5/5
DEBUG    WorkerManager:1CjMsv..uxBn Added worker: infbu64*.onion:26666, workers: 6/5
DEBUG    WorkerManager:1CjMsv..uxBn 212.24.103.*:29535: Verify failed: data/users/1JcHMiQxXHX9q3ZK2LF9rZjvg3MUtTpcK/data.json, error: Download failed, failed peers: 0, workers: 0
DEBUG    WorkerManager:1CjMsv..uxBn 7cyy64h2v4kke3u3.onion:15663: Verify correct: data/users/1JcHMiQxXHX9q3ZK2LF9rZjvg3MUtTpcK/data.json
DEBUG    Db:Horizon Connected to ./data/1CjMsvhJ2JsV4B5qo3FDHnF3mvRCcHuxBn/data/Horizon.db in 0.032s (opened: 4, sqlite version: 2.6.0)...`

Interesting that ZeroHello not reported any issue... (if there is any, i am not a programmer).
Thinking if bad file is not result of the site reaching limit during its initial load? Or when Giving access permission to ZeroTalk etc. database, if there is no colission related to size limit?

Site was DL'ed via ZeroNet not via Github.

**Comment by blurHY** [comment]
Bad file means that the file is not downloaded and needed.
The zites could know how many bad files there are.So i can let Horizon notice user if there is any bad file.(TODO already added)
