### ISSUE TITLE
**PageRank** algorithm.Using relationship data

### ISSUE THREAD

**Issue by blurHY** [blurHY/Horizon#13]

**Comment by blurHY** [comment]
Zeronet doesn't need pagerank.Just use peers count data.

**Comment by krixano** [comment]
Imo, I don't think that's a very good idea. ZeroSites does this (along with stars) and it's not very good.
I think pagerank should be based on content and how related it is to the search query - and perhaps how reliable the content is, but I'm not sure how you'd rank that.

**Comment by blurHY** [comment]
> I think pagerank should be based on content and how related it is to the search query

That may slow down the query.If it uses the normal pagerank,that can be replaced with peer count
