### ISSUE TITLE
Better logo and favicon

### ISSUE THREAD

**Issue by blurHY** [blurHY/Horizon#16]

**Comment by mirzazulfan** [comment]
Hi @blurHY ,What do you think about this?
![horizon](https://user-images.githubusercontent.com/36124339/48309607-c5c7a380-e5b0-11e8-9fc9-ba1a3897e493.png)

Idea: Letter H + Search
If you need anything change, please let me know.
Best Regard.

**Comment by blurHY** [comment]
Looks great.
Thanks.

But there is just a bit strange.
The red&gray version must be better.

**Comment by mirzazulfan** [comment]
Hi @blurHY thanks for your response, what color do you prefer? What about this?
![horizon2](https://user-images.githubusercontent.com/36124339/48356074-5bd0fc00-e68d-11e8-8b2e-a8c675b9e035.png)

**Comment by mirzazulfan** [comment]
@blurHY should i create a pr or send you all files? like .svg .png .eps .ico etc. 
![v3](https://user-images.githubusercontent.com/36124339/48657719-e176f200-ea67-11e8-8e7c-a9ee5a0050af.png)

**Comment by blurHY** [comment]
Yes,just replace the logo.png/svg and add favicon files
