### ISSUE TITLE
whole word search

### ISSUE THREAD

**Issue by veksha** [blurHY/Horizon#17]
I'm getting results as if my query is a part of some word. (for example, searching for "main" gives me "domain" results).
I need Horizon to show me whole word search results first, at the top.
Thank you.

**Comment by blurHY** [comment]
Using full text search algorithm would be better.But this needs python3.Zeronet hasn't been moved to py3 yet.If we use lots of `like` clause to simulate fts,it will be slower maybe

**Comment by blurHY** [comment]
Ok,Added
