### ISSUE TITLE
Rebranding: Poodle

### ISSUE THREAD

**Issue by DaniellMesquita** [blurHY/Horizon#20]
![start](https://user-images.githubusercontent.com/6765277/51883488-38534e80-236a-11e9-8285-d4226c33f9c3.png)
Above, the icon to show on start page.

Logotype to show on header when searching:
![logotype](https://user-images.githubusercontent.com/6765277/51883501-4012f300-236a-11e9-95fc-e33c961d8694.png)

Brand icon/favicon:
![icon](https://user-images.githubusercontent.com/6765277/51883512-528d2c80-236a-11e9-9234-ce07b223a1e6.png)

The rebranding doesn't only consists on new name/font/logotype/icon, but also a new design and a new concept: working also outside ZeroNet.

My idea is that Poodle could also work on Dat and IPFS, and provide results for their sites.
When showing results of Dat/IPFS/ZeroNet, when not on these networks, show an download link.

**Comment by DaniellMesquita** [comment]
Posted on Peepeth about the Poodle project: https://peepeth.com/daniellmesquita/peeps/QmbGkZeXCQZjf75go5MTN65iU2achrs7qLJvLkETZa1ymr

**Comment by blurHY** [comment]
But I don't know much about IPFS and Dat

**Comment by DaniellMesquita** [comment]
@blurHY what do you think?

**Comment by DaniellMesquita** [comment]
@blurHY what do you think?

**Comment by DaniellMesquita** [comment]
> But I don't know much about IPFS and Dat

I could help you to make it work on Dat, while I'm also learning about IPFS.
Do you like the idea of an hybrid search engine? Did you liked the new design of the brand and the new name?

**Comment by blurHY** [comment]
Is there any existing search engine on IPFS and Dat.We could just mix their search result like DuckDuckGo.
If we choose to build one, where do we host the search engine to be decentralized ?

**Comment by DaniellMesquita** [comment]
> Is there any existing search engine on IPFS and Dat.We could just mix their search result like DuckDuckGo.
> If we choose to build one, where do we host the search engine to be decentralized ?

Makes sense, and using YaCy will make that possible:
https://yacy.net/en/index.html
https://github.com/beakerbrowser/beaker/issues/993#issuecomment-392308048

**Comment by DaniellMesquita** [comment]
@shortcutme, what do you think about supporting YaCy on ZeroNet? Like I've suggested about SharedSearch plugin.
YaCy should also support IPFS/Dat/ZeroNet protocols.

**Comment by blurHY** [comment]
YaCy is just a distributed web spider,isn't it?

**Comment by DaniellMesquita** [comment]
> Is there any existing search engine on IPFS and Dat.

For Dat, there is no search engine yet (then Poodle will be very handy).
For IPFS, there is:
https://ipfs-search.com/
https://github.com/ipfs-search/ipfs-search

**Comment by DaniellMesquita** [comment]
> YaCy is just a distributed web spider,isn't it?

Yes, and it is amazing.
You should use it as helper of your own spider.

**Comment by DaniellMesquita** [comment]
> If we choose to build one, where do we host the search engine to be decentralized ?

It's already on ZeroNet.
Poodle can also be hosted on Dat and IPFS.
Could you download Beaker browser to test Dat and create an site for Horizon/Poodle?
https://github.com/beakerbrowser/beaker

Then, please share here the dat URL.

**Comment by blurHY** [comment]
I can't use beaker browser.It's not working in China maybe.
So I'm not interested in it.

But IPFS works,just consumes too much CPU.And I shutdown it

**Comment by DaniellMesquita** [comment]
> I can't use beaker browser.It's not working in China maybe.
> So I'm not interested in it.

Could I pull request with a rebrand for Horizon? And upload/maintain it on Dat?
We could joint our efforts to make this engine even better.

**Comment by blurHY** [comment]
![image](https://user-images.githubusercontent.com/33171396/51885384-299a8500-23c6-11e9-9f4c-7026f6b6f840.png)
How to make it works

**Comment by DaniellMesquita** [comment]
> But IPFS works,just consumes too much CPU.And I shutdown it

Did you tried to limit the peers you're connected to?

Reference: https://github.com/ipfs/go-ipfs/issues/2945, https://github.com/ipfs/go-ipfs/issues/4531, https://github.com/ipfs/go-ipfs/issues/3318

**Comment by DaniellMesquita** [comment]
> How to make it works

Is your Internet connection slow?
Here I also gets these errors, when using 3G.

You could report that on Beaker's repo.
Probably GFW blocked Dat.

**Comment by DaniellMesquita** [comment]
Anyway, you can still choose the ZN's Horizon folder and make it an Dat site, to work on both networks.

**Comment by blurHY** [comment]
I think we can share the technology, but we should not make it one brand.It's not necessary.
Because zeronet is not compatible with Dat.

**Comment by DaniellMesquita** [comment]
> I think we can share the technology, but we should not make it one brand.It's not necessary.
> Because zeronet is not compatible with Dat.

Compatibility doesn't matter.
An Cordova app isn't compatible with Desktop, but when adding Electron codes to the build, it turns into an hybrid app.

The idea is not just to show Dat results on ZeroNet (while offering download link for Dat/Beaker), but also showing ZeroNet results on Dat (and offering download link for ZeroNet). The same with IPFS (we could mix search results using the engine of IPFS-Search, being an beauty and hybrid frontend for that).

**Comment by DaniellMesquita** [comment]
There is a little CSS error on settings button, when adding a logo with another size:
![image](https://user-images.githubusercontent.com/6765277/51916096-bbed5980-23c3-11e9-92a1-5ac2cadc1ee6.png)
I'll fix that. I'm using Horizon V1 until V2 is ready. I don't like to make Horizon closed while V2 isn't out, but use V1 while that.

**Comment by DaniellMesquita** [comment]
@blurHY some news about ZN working on your country? Does Horizon uses pure JS to show search results?

**Comment by blurHY** [comment]
@DaniellMesquita I'm writing the third version of HorizonSpider and going to build a centralized Horizon search.
I joined a team and created v4ww org with them.
We sent some emails to d14na and they said they would use our spider.
They think zeronet is more important than IPFS.
In addition, our team and d14na both want to rewrite zeronet with nodejs (or maybe other lang).
I feel shortcutme doesn't want to add any features to zeronet, and now zeronet is dead in China.
I reported GFW problems to IPFS, they at least think about it.
But shortcutme did nothing and threw Chinese users away. 

Do you want to join us?

**Comment by DaniellMesquita** [comment]
> @DaniellMesquita I'm writing the third version of HorizonSpider and going to build a centralized Horizon search.
I joined a team and created v4ww org with them.
We sent some emails to d14na and they said they would use our spider.
They think zeronet is more important than IPFS.
In addition, our team and d14na both want to rewrite zeronet with nodejs (or maybe other lang).
I feel shortcutme doesn't want to add any features to zeronet, and now zeronet is dead in China.
I reported GFW problems to IPFS, they at least think about it.
But shortcutme did nothing and threw Chinese users away.

Do you want to join us?

Mkg is already creating a JS version of ZN, and probably will join you. And I can join supporting with suggestions and designs.

The search can be hybrid, on ZeroNet and with a centralized version for clearnet results.

**Comment by blurHY** [comment]
Hybird what ?

**Comment by DaniellMesquita** [comment]
Horizon, or Poodle; it can be hybrid, working on both ZeroNet and clearnet

**Comment by blurHY** [comment]
Decentralized search site ?

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by blurHY** [comment]
We planned to build a new zeronet on the top of ipfs instead.

**Comment by DaniellMesquita** [comment]
> We planned to build a new zeronet on the top of ipfs instead.

Please send an repo so we create an issue for discuss that

**Comment by DaniellMesquita** [comment]
> Decentralized search site ?

And also centralized (clearnet), so it is hybrid

**Comment by blurHY** [comment]
> > Decentralized search site ?
> 
> And also centralized (clearnet), so it is hybrid

Full-decentralized may be not possible.

**Comment by blurHY** [comment]
Repo created https://github.com/v4ww/ZeroNetOverIPFS/issues

**Comment by DaniellMesquita** [comment]
@blurHY
> We planned to build a new zeronet on the top of ipfs instead.
> Repo created https://github.com/v4ww/ZeroNetOverIPFS/issues

I'm creating ZeroNet+, which includes ZeroNet+Dat+IPFS. Users could have multiple identities: Dat's own, ZeroNet BTC identy, IPFS' ETH, etc.

> Full-decentralized may be not possible.

IPFS haves OrbitDB, which is decentralized and scalable for a search engine.

Do you use Riot.im?

**Comment by DaniellMesquita** [comment]
Poodle search now available on Dat:
dat://cf59f102b716e016a5f4d4d9610b5ee8669106ed91a0b5a9eded0736ba5e2fe6/
![image](https://user-images.githubusercontent.com/6765277/57901118-02af7400-783a-11e9-8996-426a5fabc6b1.png)

**Comment by blurHY** [comment]
The next project I will work on is the ZeroNet over IPFS.
What do you think of?

**Comment by slrslr** [comment]
> Repo created https://github.com/v4ww/ZeroNetOverIPFS/issues
this is 404 page atm. What bother me on ZN is duplicate files (one in normal dir, and up to several others in zeronet subdirectories), if ZN+IPFS will solve this (at least getting rid of duplicities in "zeronet dir"), i would use it and report issues of it. Ofcourse ZN+IPFS should be compatible with main ZN functions so one can browse existing media sites like K0pykate.

**Comment by blurHY** [comment]
IPFS solves it

**Comment by blurHY** [comment]
https://github.com/blurHY/Axonet/issues

**Comment by DaniellMesquita** [comment]
@blurHY 
I understand you need to focus on ZN+IPFS instead of your search engine.
We're discussing about it, but on Poodle search rebranding issue.
I'll keep the Poodle search project (outside of this search engine), and you're welcome to create a ZN version of Poodle search.

**Comment by blurHY** [comment]
Search engine will also be planned when the new network grows bigger. AFAIK, there're only 6000 downloadable sites on zeronet. So it is not meaningful.
IPFS already has a search engine called ipfs-search
Dat network is obviously smaller than zeronet

And the name poodle is a dog, which isn't good in China.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gesundelehre** [comment]
Hello there,

does anyone know something about the current status of the search-engine?
If it is still running, could someone put it up on dat again so i could download it?

Thanks in advance

**Comment by danimesq** [comment]
Do you use Beaker?

**Comment by blurHY** [comment]
No, currently this search engine is abandoned, because a centralized search engine won't help the decentralized web much.

Horizon uses general method to crawl sites, so it's not the best solution on DHT powered networks.

I'm considering a decentralized search engine on IPZN, incentived with blockchain.

https://gitlab.com/ipzn/ipzn/
